name: chess-classifier
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pytest=5.0.1
  - pytest-cov
  - flake8=3.8.1
  - pip
  - click=7.0
  - numpy=1.16.4
  - pandas=1.0.4
  - tqdm
  - vaex
  - xarray
  - dask=2.1.0
  - tqdm
  - pip:
    - dvc[s3]==0.93.0
    - tensorflow==2.0.0-alpha0
    - python-chess
    - seaborn
    - scikit-learn